=== xtinuz/IVH5A2-Herkansing/fysiotherapeut/target/resources/data/library-extended.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.avans.nl/ivh5/worked-example/extended"
	xmlns:lib="http://www.avans.nl/ivh5/worked-example/extended">

	<element name="Library">
		<complexType>
			<sequence>
				<element name="Member" type="lib:MemberType" maxOccurs="unbounded"
					minOccurs="1"></element>
				<element name="Item" type="lib:ItemType" maxOccurs="unbounded"
					minOccurs="1"></element>
				<element name="Author" type="lib:AuthorType" maxOccurs="unbounded"
					minOccurs="1"></element>
				<element name="Actor" type="lib:ActorType" maxOccurs="unbounded"
					minOccurs="1"></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="MemberType">
		<sequence>
			<element name="Firstname" type="string" minOccurs="1"></element>
			<element name="Lastname" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="Address" type="lib:AddressType" minOccurs="1" maxOccurs="3"></element>
			<element name="TelephoneNumbers" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="TelephoneNumber" type="lib:TelephoneNumberType" minOccurs="1" maxOccurs="3"></element>
					</sequence>
				</complexType>
			</element>
			<element name="EmailAddress" type="string"></element>
			<element name="Fine" type="double"></element>
			<element name="Loans">
				<complexType>
					<sequence>
						<element name="Loan" type="lib:LoanType" maxOccurs="5" minOccurs="0"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
		<attribute name="MembershipNumber" type="positiveInteger"></attribute>
	</complexType>

	<complexType name="AddressType">
		<sequence>
			<element name="Street" type="string"></element>
			<element name="Housenumber" type="positiveInteger"></element>
			<element name="City" type="string"></element>
		</sequence>
		<attribute name="addressKind" type="lib:addressKindType"></attribute>
	</complexType>
	
	<simpleType name="addressKindType">
		<restriction base="string">
			<enumeration value="Primary Address"></enumeration>
			<enumeration value="Postal Address"></enumeration>
			<enumeration value="Alternative Address"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="ItemType">
		<sequence>
			<element name="Category" type="lib:ItemCategoryType" minOccurs="1"></element>
			<choice>
				<annotation>
					<documentation>Choose the correct item type.</documentation>
				</annotation>
				<element name="Book" type="lib:BookType"></element>
				<element name="Movie" type="lib:MovieType"></element>
			</choice>
			<element name="PublicationDate" type="date"	minOccurs="0"></element>
		</sequence>
		<attribute name="itemNumber" type="nonNegativeInteger"></attribute>
	</complexType>

	<simpleType name="ItemCategoryType">
		<restriction base="string">
			<enumeration value="Thriller"></enumeration>
			<enumeration value="Literature"></enumeration>
			<enumeration value="Action and Adventure"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="TelephoneNumberType">
		<sequence>
			<element name="Number" minOccurs="1" maxOccurs="1"></element>
		</sequence>
		<attribute name="NumberType" type="lib:TypeOfPhone"></attribute>
	</complexType>
	
	<simpleType name="TypeOfPhone">
		<restriction base="string">
			<enumeration value="Home"></enumeration>
			<enumeration value="Mobile"></enumeration>
			<enumeration value="Work"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="FormatType">
		<restriction base="string">
			<enumeration value="Hardcover"></enumeration>
			<enumeration value="Paperback"></enumeration>
			<enumeration value="DVD"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="LanguageType">
		<restriction base="string">
			<enumeration value="Dutch"></enumeration>
			<enumeration value="English"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="BookType">
		<sequence>
			<element name="ISBN" type="lib:ISBNType" minOccurs="1" maxOccurs="1"></element>
			<element name="Title" type="string" minOccurs="1" maxOccurs="2"></element>
			<element name="Author" type="string" minOccurs="1" maxOccurs="unbounded"></element>
			<element name="Format" type="lib:FormatType" minOccurs="1" maxOccurs="1"></element>
			<element name="Publisher" type="string" minOccurs="0"></element>
			<element name="Language" type="lib:LanguageType" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="MovieType">
		<sequence>
			<element name="EAN" minOccurs="1" maxOccurs="1">
				<simpleType>
					<restriction base="string">
						<minLength value="8"/>
						<maxLength value="10"/>
					</restriction>
				</simpleType>
			</element>
			<element name="Format" type="lib:FormatType" minOccurs="1" maxOccurs="1"></element>
			<element name="Title" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="Director" type="string" minOccurs="1" maxOccurs="5"></element>
			<element name="Actors" type="lib:ActorsType" minOccurs="1" maxOccurs="1"></element>			
		</sequence>
	</complexType>

	<complexType name="ActorsType">
		<sequence>
			<element name="ActorName" type="string"  minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="AuthorType">
		<sequence>
			<element name="Name" type="string"></element>
			<element name="CountryOfBirth" type="string"></element>
			<element name="BirthDate" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="ActorType">
		<sequence>
			<element name="Name" type="string"></element>
			<element name="CountryOfBirth" type="string"></element>
			<element name="BirthDate" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="LoanType">
		<sequence>
			<element name="ItemNumber" type="nonNegativeInteger" maxOccurs="1" minOccurs="1"></element>
			<element name="LendingDate" type="date" maxOccurs="1" minOccurs="1"></element>
		</sequence>
		<attribute name="CopyID" type="positiveInteger"></attribute>
		<attribute name="LendingPeriod" type="positiveInteger"></attribute>
	</complexType>

	<simpleType name="ISBNType">
	    <restriction base="integer">
	      	<pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
	    </restriction>
	</simpleType>

</schema>

=== xtinuz/IVH5A2-Herkansing/fysiotherapeut/target/resources/data/library-extended.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="library.xsl"?>

<lib:Library xmlns:lib="http://www.avans.nl/ivh5/worked-example/extended" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.avans.nl/ivh5/worked-example/extended library-extended.xsd">

	<Member MembershipNumber="1004">
		<Firstname>Robin</Firstname>
		<Lastname>Schellius</Lastname>
		<Address addressKind="Primary Address">
			<Street>Hierdestraat</Street>
			<Housenumber>5</Housenumber>
			<City>Breda</City>
		</Address>
		<Address addressKind="Postal Address">
			<Street>Verderop</Street>
			<Housenumber>12</Housenumber>
			<City>Ulicoten</City>
		</Address>
		<TelephoneNumbers>
			<TelephoneNumber NumberType="Home">
				<Number>076-1968201</Number>
			</TelephoneNumber>
			<TelephoneNumber NumberType="Mobile">
				<Number>06-19682014</Number>
			</TelephoneNumber>
		</TelephoneNumbers>
		<EmailAddress>r.schellius@avans.nl</EmailAddress>
		<Fine>2.75</Fine>
		<Loans>
			<Loan CopyID="2" LendingPeriod="3">
				<ItemNumber>857865544</ItemNumber>
				<LendingDate>2014-06-28</LendingDate>
			</Loan>
			<Loan CopyID="1" LendingPeriod="2">
				<ItemNumber>834586544</ItemNumber>
				<LendingDate>2014-06-28</LendingDate>
			</Loan>
		</Loans>
	</Member>

	<Item itemNumber="1000001">
		<Category>Action and Adventure</Category>
		<Book>
			<ISBN>857865544</ISBN>
			<Title>The life of Pi</Title>
			<Author>Yann Martel</Author>
			<Format>Paperback</Format>
			<Publisher>Mariner Books</Publisher>
			<Language>English</Language>
		</Book>
		<PublicationDate>2003-05-01</PublicationDate>
	</Item>
	<Item itemNumber="1000002">
		<Category>Literature</Category>
		<Book>
			<ISBN>857812365</ISBN>
			<Title>The Old Man and the Sea</Title>
			<Author>Ernest Hemingway</Author>
			<Format>Hardcover</Format>
			<Publisher>Charles Scribner's Sons</Publisher>
			<Language>English</Language>
		</Book>
		<PublicationDate>1952-01-01</PublicationDate>
	</Item>
	<Item itemNumber="1000003">
		<Category>Thriller</Category>
		<Movie>
			<EAN>8711875926</EAN>
			<Format>DVD</Format>
			<Title>The Sixth Sense</Title>
			<Director>M. Night Shyamalan</Director>
			<Actors>
				<ActorName>Bruce Willis</ActorName>
				<ActorName>Haley Joel Osmond</ActorName>
				<ActorName>Tony Colette</ActorName>
			</Actors>
		</Movie>
		<PublicationDate>1999-01-01</PublicationDate>
	</Item>
	
	<Author>
		<Name>Yann Martel</Name>
		<CountryOfBirth>Spain</CountryOfBirth>
		<BirthDate>1963</BirthDate>
	</Author>
	<Author>
		<Name>Ernest Hemingway</Name>
		<CountryOfBirth>United States</CountryOfBirth>
		<BirthDate>1899</BirthDate>
	</Author>
	
	<Actor>
		<Name>Bruce Willis</Name>
		<CountryOfBirth>United States</CountryOfBirth>
		<BirthDate>1955-03-19</BirthDate>
	</Actor>
	
</lib:Library>
