=== xtinuz/IVH5A2-Herkansing/fysiotherapeut/target/resources/data/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.avans.nl/ivh5/worked-example"
	xmlns:lib="http://www.avans.nl/ivh5/worked-example">

    <element name="library">
		<complexType>
           <sequence>
				<element name="members">
					<complexType>
			            <sequence>
				    		<element name="member" type="lib:MemberType" maxOccurs="unbounded" minOccurs="0"></element>
			            </sequence>
					</complexType>
				</element>
				<element name="items">
					<complexType>
			            <sequence>
				    		<element name="book" type="lib:BookType" maxOccurs="unbounded" minOccurs="0"></element>
			            </sequence>
					</complexType>
				</element>
            </sequence>
		</complexType>
    </element>

    <complexType name="BookType">
    	<sequence>
    		<element name="isbn" type="lib:ISBNType"></element>
    		<element name="title" type="string"></element>
    		<element name="author" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="MemberType">
    	<sequence>
    		<element name="firstname" type="string" minOccurs="1"></element>
    		<element name="lastname" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="street" type="string"></element>
    		<element name="housenumber" type="positiveInteger"></element>
    		<element name="city" type="string"></element>
    		<element name="phoneNumber" type="string"></element>
    		<element name="emailaddress" type="string"></element>
    		<element name="fine" type="double"></element>
	        <element name="loans">
	          <complexType>
	            <sequence>
		    		<element name="loan" type="lib:LoanType" maxOccurs="unbounded" minOccurs="0"></element>
	            </sequence>
	          </complexType>
	        </element>
    	</sequence>
	    <attribute name="membershipNumber" type="positiveInteger"></attribute>
    </complexType>
    
    <complexType name="LoanType">
    	<sequence>
    		<element name="isbn" type="lib:ISBNType"  maxOccurs="1"  minOccurs="1"></element>
    	</sequence>
    	<attribute name="copyid" type="positiveInteger"></attribute>
    	<attribute name="lendingperiod" type="positiveInteger"></attribute>
    </complexType>

    <simpleType name="ISBNType">
    	<restriction base="positiveInteger"></restriction>
    </simpleType>

</schema>

=== xtinuz/IVH5A2-Herkansing/fysiotherapeut/target/resources/data/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="library.xsl"?>

<lib:library xmlns:lib="http://www.avans.nl/ivh5/worked-example" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.avans.nl/ivh5/worked-example library.xsd">

	<members>
		<member membershipNumber="1004">
			<firstname>Robin</firstname>
			<lastname>Schellius</lastname>
			<street>Hierdestraat</street>
			<housenumber>5</housenumber>
			<city>Breda</city>
			<phoneNumber>076-19682014</phoneNumber>
			<emailaddress>r.schellius@avans.nl</emailaddress>
			<fine>2.75</fine>
			<loans>
				<loan copyid="2" lendingperiod="3">
					<isbn>857865544</isbn>
				</loan>
				<loan copyid="1" lendingperiod="2">
					<isbn>834586544</isbn>
				</loan>
			</loans>
		</member>
		<member membershipNumber="1005">
			<firstname>Jan-Willem</firstname>
			<lastname>Van Dalen</lastname>
			<street>Bergenseweg</street>
			<housenumber>28</housenumber>
			<city>Roosendaal</city>
			<phoneNumber>076-19722014</phoneNumber>
			<emailaddress>jwvdalen@gmail.com</emailaddress>
			<fine>6.45</fine>
			<loans>
				<loan copyid="2" lendingperiod="1">
					<isbn>834586544</isbn>
				</loan>
			</loans>
		</member>
		<member membershipNumber="1010">
			<firstname>Robert</firstname>
			<lastname>Verdullemen</lastname>
			<street>Overkant</street>
			<housenumber>5</housenumber>
			<city>Hierde</city>
			<phoneNumber>046-19682014</phoneNumber>
			<emailaddress>rdj.verdullemen@avans.nl</emailaddress>
			<fine>3.75</fine>
			<loans>
				<loan copyid="2" lendingperiod="3">
					<isbn>857865244</isbn>
				</loan>
				<loan copyid="1" lendingperiod="2">
					<isbn>834286544</isbn>
				</loan>
			</loans>
		</member>
		<member membershipNumber="1011">
			<firstname>Marieke</firstname>
			<lastname>Van Zwieten</lastname>
			<street>Bredaseweg</street>
			<housenumber>12</housenumber>
			<city>Ulicoten</city>
			<phoneNumber>076-19682014</phoneNumber>
			<emailaddress>mrj.vanzwieten@breda.nl</emailaddress>
			<fine>0.0</fine>
			<loans>
				<loan copyid="2" lendingperiod="3">
					<isbn>857865244</isbn>
				</loan>
			</loans>
		</member>
	</members>

	<items>
		<book>
			<isbn>857865544</isbn>
			<title>The life of Pi</title>
			<author>Yann Martel</author>
		</book>
		<book>
			<isbn>834586544</isbn>
			<title>The old man and the sea</title>
			<author>Ernest Hemingway</author>
		</book>
	</items>
	
</lib:library>
