=== xtinuz/IVH5A2-Herkansing/fysiotherapeut/server/resources/physiopractice.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.avans.nl/ivh5/worked-example"
	xmlns:lib="http://www.avans.nl/ivh5/worked-example">

    <element name="">
		<complexType>
           <sequence>
				<element name="physiopractice">
					<element name="name" type="string"></element>
					<element name="address" type="string"></element>
					<element name="postal" type="string"></element>
					<element name="city" type="string"></element>
					<element name="phone" type="string"></element>
					<element name="email" type="string"></element>
					<element name="kvk" type="string"></element>
					<element name="iban" type="string"></element>
					<element name="bic" type="string"></element>
					<element name="bank" type="string"></element>
				</element>
				
            </sequence>
		</complexType>
    </element>
</schema>

=== xtinuz/IVH5A2-Herkansing/fysiotherapeut/server/resources/physiopractice.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><physiopractice xmlns:lib="http://www.avans.nl/ivh5/worked-example" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.avans.nl/ivh5/worked-example physiopractice.xsd">
	<name>Zorg4me</name>
	<address>Straat 123A</address>
	<postal>1234AB</postal>
	<city>Breda</city>
	<phone>0698765432</phone>
	<email>info@zorg4u.nl</email>
	<kvk>12312312</kvk>
	<iban>NL91ABNA0417164300</iban>
	<bic>ABNANL2A</bic>
	<bank>ABN Amro</bank>
</physiopractice>
